import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chat-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/" />
      </Head>
      <main>
        <div>
          <p>
            chat-app
          </p>
        </div>
      </main>
    </>
  )
}

export default Page